/* GENERATED by scripts/build_web.py from web-shared/src/vn-app.jsx — do not edit; edit the source and rebuild. source-sha256=cd32a58f709061ba7386ea68a17d228b0571ff81a881700f13d3c10d70c07842 */
function ownKeys(e, r) { var t = Object.keys(e); if (Object.getOwnPropertySymbols) { var o = Object.getOwnPropertySymbols(e); r && (o = o.filter(function (r) { return Object.getOwnPropertyDescriptor(e, r).enumerable; })), t.push.apply(t, o); } return t; }
function _objectSpread(e) { for (var r = 1; r < arguments.length; r++) { var t = null != arguments[r] ? arguments[r] : {}; r % 2 ? ownKeys(Object(t), !0).forEach(function (r) { _defineProperty(e, r, t[r]); }) : Object.getOwnPropertyDescriptors ? Object.defineProperties(e, Object.getOwnPropertyDescriptors(t)) : ownKeys(Object(t)).forEach(function (r) { Object.defineProperty(e, r, Object.getOwnPropertyDescriptor(t, r)); }); } return e; }
function _defineProperty(e, r, t) { return (r = _toPropertyKey(r)) in e ? Object.defineProperty(e, r, { value: t, enumerable: !0, configurable: !0, writable: !0 }) : e[r] = t, e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == typeof i ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != typeof t || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != typeof i) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
/* vn-app.jsx — the web-VN-v2 (dubaomua) dashboard app (JSX source).
 * Compiled by scripts/build_web.py into web-VN-v2/app.js;
 * after editing: run the build and bump ?v= on app.js in that index.html.
 * Runs after dashboard-core.js, which provides window.QPFShared. */
const {
  useState,
  useEffect,
  useMemo,
  useRef
} = React;
const {
  MODEL_COLOR,
  FIELDS,
  FIELD_ORDER,
  j,
  dmy,
  dm,
  dow,
  hhmm,
  num,
  norm,
  binsFor,
  colorFor,
  winTiles,
  stepTiles,
  PAD,
  niceMax,
  Axes,
  Timeline,
  OffGridNote,
  Credit,
  attachTcOverlay,
  TcBanner,
  escHtml
} = window.QPFShared;
const MODES = [{
  key: "tinh",
  label: "Tỉnh / Thành"
}, {
  key: "xa",
  label: "Phường / Xã"
}, {
  key: "grid",
  label: "Ô lưới"
}];
// Unit (polygon) values are area-weighted 24-h window aggregates — per-step
// int/cum only exist on the raster, so those two fields are grid-mode-only.
const UNIT_FIELDS = ["q50", "q90", "x50"];

// value arrays for a unit level: frames.json for the five ensemble sources,
// gm_frames.json for VForce-cast (fields listed in meta.gm.fields)
function unitValues(frames, gm, level, model, field, winIdx) {
  if (model === "vforce") {
    const g = gm && gm[level];
    if (!g || !g[field]) return null;
    const arr = g[field][winIdx];
    if (!arr) return null;
    const o = {};
    (g.ids || []).forEach((id, i) => o[id] = arr[i]);
    return o;
  }
  const lv = frames && frames[level];
  if (!lv) return null;
  const s = (lv.sources || {})[model];
  if (!s || !s[field]) return null;
  const arr = s[field][winIdx];
  if (!arr) return null;
  const o = {};
  (lv.ids || []).forEach((id, i) => o[id] = arr[i]);
  return o;
}

/* ------------------------------------------------------------------ map */
function MapPane({
  mode,
  meta,
  tmeta,
  geo,
  frames,
  gm,
  model,
  field,
  frameIdx,
  ver,
  winCount,
  onPick,
  focusId,
  onPickGrid,
  zoomTo,
  tc,
  onTcLead,
  tcSync
}) {
  const elRef = useRef(null),
    mapRef = useRef(null),
    rasterRef = useRef(null);
  const layerRef = useRef(null),
    perIdRef = useRef({}),
    modeRef = useRef(null);
  const [zoom, setZoom] = useState(6);
  const adminRef = useRef(null),
    adminXaRef = useRef(null),
    adminFgRef = useRef(null);
  const onPickRef = useRef(onPick);
  onPickRef.current = onPick;
  const onGridRef = useRef(onPickGrid);
  onGridRef.current = onPickGrid;
  const modeVal = useRef(mode);
  modeVal.current = mode;
  const bins = binsFor(field, meta.legend);
  useEffect(() => {
    const map = L.map(elRef.current, {
      preferCanvas: true,
      zoomControl: false,
      minZoom: 4,
      maxZoom: 12
    }).setView([16.2, 106.4], 6);
    L.control.zoom({
      position: "topright"
    }).addTo(map);
    L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}", {
      attribution: "Tiles &copy; Esri",
      maxZoom: 16,
      maxNativeZoom: 16
    }).addTo(map);
    map.createPane("raster");
    map.getPane("raster").style.zIndex = 200;
    map.createPane("admin");
    map.getPane("admin").style.zIndex = 400;
    map.getPane("admin").style.pointerEvents = "none";
    map.createPane("labels");
    map.getPane("labels").style.zIndex = 655;
    map.getPane("labels").style.pointerEvents = "none";
    L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer/tile/{z}/{y}/{x}", {
      maxZoom: 16,
      maxNativeZoom: 16,
      pane: "labels"
    }).addTo(map);
    // Vietnamese island groups, labelled prominently like a major city
    [[16.5, 112.0, "quần đảo Hoàng Sa<br>(Việt Nam)"], [9.7, 113.8, "quần đảo Trường Sa<br>(Việt Nam)"]].forEach(([la, lo, txt]) => L.marker([la, lo], {
      pane: "labels",
      interactive: false,
      icon: L.divIcon({
        className: "island-label",
        html: txt,
        iconSize: [150, 34],
        iconAnchor: [75, 17]
      })
    }).addTo(map));
    // in Ô lưới mode a click on the basemap queries the VForce-cast cell
    map.on("click", e => {
      if (modeVal.current === "grid") onGridRef.current(e.latlng);
    });
    map.on("zoomend", () => setZoom(map.getZoom()));
    mapRef.current = map;
    return () => map.remove();
  }, []);

  // ------ grid mode: pre-rendered PNG rasters, identical to the dam map
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !tmeta) return;
    const on = mode === "grid";
    const M = tmeta.models[model];
    if (!on || !M || !M.fields.includes(field)) {
      if (rasterRef.current) {
        map.removeLayer(rasterRef.current);
        rasterRef.current = null;
      }
      return;
    }
    const [s, w, n, e] = M.bounds;
    const b = [[s, w], [n, e]];
    const url = `tiles/${model}/${field}/${String(frameIdx).padStart(2, "0")}.png?v=${encodeURIComponent(ver)}`;
    if (!rasterRef.current) rasterRef.current = L.imageOverlay(url, b, {
      opacity: .74,
      pane: "raster",
      interactive: false
    }).addTo(map);else {
      rasterRef.current.setUrl(url);
      rasterRef.current.setBounds(b);
      if (!map.hasLayer(rasterRef.current)) rasterRef.current.addTo(map);
    }
  }, [mode, tmeta, model, field, frameIdx, ver]);

  // Zoom to a searched unit. `zoomTo` is {bounds:[w,s,e,n],n} — the counter n
  // makes picking the SAME unit twice still fire (bounds alone would be an
  // unchanged dependency).
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !zoomTo || !zoomTo.bounds) return;
    const [w, so, e, no] = zoomTo.bounds;
    map.fitBounds([[so, w], [no, e]], {
      padding: [40, 40],
      maxZoom: 11
    });
  }, [zoomTo]);

  // ------ Ô lưới: admin outlines over the raster. The raster alone gives no
  // sense of WHERE a cell is, so provinces are always outlined and communes
  // fade in once the zoom makes them legible. Non-interactive pane so the
  // point query still receives the click.
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    const on = mode === "grid";
    const drop = r => {
      if (r.current) {
        map.removeLayer(r.current);
        r.current = null;
      }
    };
    if (!on) {
      drop(adminRef);
      drop(adminXaRef);
      drop(adminFgRef);
      return;
    }
    // opacities are half the first pass — the outlines are orientation aids,
    // they must not compete with the rainfall raster underneath
    if (geo.tinh && !adminRef.current) {
      adminRef.current = L.geoJSON(geo.tinh, {
        pane: "admin",
        interactive: false,
        style: () => ({
          color: "#243746",
          weight: 1.3,
          opacity: .45,
          fill: false
        })
      }).addTo(map);
    }
    // neighbouring-country provinces: the raster spans 94-120 E, so without
    // these only Vietnam would have any admin reference
    if (geo.adm1 && !adminFgRef.current) {
      adminFgRef.current = L.geoJSON(geo.adm1, {
        pane: "admin",
        interactive: false,
        style: () => ({
          color: "#3a4a5a",
          weight: 0.9,
          opacity: .32,
          fill: false
        })
      }).addTo(map);
    }
    if (zoom >= 8 && geo.xa && !adminXaRef.current) {
      adminXaRef.current = L.geoJSON(geo.xa, {
        pane: "admin",
        interactive: false,
        style: () => ({
          color: "#4a5b6b",
          weight: 0.5,
          opacity: .28,
          fill: false
        })
      }).addTo(map);
    }
    if (zoom < 8) drop(adminXaRef);
    if (adminRef.current) adminRef.current.bringToFront();
  }, [mode, geo, zoom]);

  // ------ unit modes: one geoJSON layer per level, recoloured in place
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    const level = mode === "grid" ? null : mode;
    // rebuild when the mode changes OR when the geojson for the current level
    // arrives after the first render (xa.geojson loads late)
    if (modeRef.current !== level || level && !layerRef.current && geo[level]) {
      if (layerRef.current) {
        map.removeLayer(layerRef.current);
        layerRef.current = null;
        perIdRef.current = {};
      }
      modeRef.current = level;
      if (level && geo[level]) {
        const lyr = L.geoJSON(geo[level], {
          style: () => ({
            weight: level === "xa" ? 0.35 : 0.8,
            color: "#8fa1b3",
            fillOpacity: .85,
            fillColor: "#eef2f6"
          }),
          onEachFeature: (f, l) => {
            perIdRef.current[f.properties.id] = l;
            l.bindTooltip(escHtml(f.properties.ten), {
              sticky: true,
              className: "unit-tip"
            });
            // click opens the time-series drawer (replaces the old popup —
            // charts tell the story a 4-row table could not)
            l.on("click", () => onPickRef.current(f.properties));
          }
        }).addTo(map);
        layerRef.current = lyr;
      }
    }
    if (!level || !layerRef.current) return;
    const vals = unitValues(frames, gm, level, model, field, frameIdx) || {};
    const win = model === "vforce" && meta.gm ? meta.gm.windows[frameIdx] : null;
    // per-source window axis (model_windows) — a 6-hourly model's frames sit
    // on its own ends, so label from ITS axis, not the shared ensemble one
    const mw = ((meta.model_windows || {})[model] || [])[frameIdx];
    const winLab = model === "vforce" ? win ? `+${win.lead_h}h (VForce-cast)` : "" : mw ? `+${mw.lead_h}h` : meta.windows[frameIdx] ? `+${24 * (frameIdx + 1)}h` : "";
    Object.entries(perIdRef.current).forEach(([id, l]) => {
      const v = vals[id];
      const col = colorFor(v, bins);
      const sel = id === focusId;
      l.setStyle({
        fillColor: col || "#eef2f6",
        fillOpacity: col ? .85 : .45,
        color: sel ? "#12324d" : "#8fa1b3",
        weight: sel ? 2.4 : level === "xa" ? 0.35 : 0.8
      });
      if (sel) l.bringToFront();
      l.bindTooltip(`${escHtml(l.feature.properties.ten)} — ${num(v, field === "x50" ? 0 : 1)} ${FIELDS[field].unit}`, {
        sticky: true,
        className: "unit-tip"
      });
    });
  }, [mode, geo, frames, gm, model, field, frameIdx, bins, meta, winCount, focusId]);

  // cyclone overlay (optional tc.json) — own panes, never swallows the
  // province clicks; redrawn only when the tc data changes. onLead (via a
  // ref, so the overlay is not rebuilt per render) lets the TC player drive
  // the rainfall raster to the same valid time.
  const onTcLeadRef = useRef(onTcLead);
  onTcLeadRef.current = onTcLead;
  const tcApiRef = useRef(null);
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !tc) return;
    const api = attachTcOverlay(map, tc, {
      onLead: (h, ms) => onTcLeadRef.current && onTcLeadRef.current(h, ms)
    });
    tcApiRef.current = api;
    return () => {
      tcApiRef.current = null;
      api();
    };
  }, [tc]);
  // reverse sync: the rain timeline (play or frame click) drives the
  // cyclone display to the same valid time
  useEffect(() => {
    if (tcSync && tcApiRef.current) tcApiRef.current.syncTo?.(tcSync.t, tcSync.gate);
  }, [tcSync]);
  return /*#__PURE__*/React.createElement("div", {
    id: "map",
    ref: elRef
  });
}

/* ---------------------------------------------------------- unit card */
// Clicking a Tỉnh/Phường-Xã no longer opens the in-app time-series drawer:
// every unit has a standalone page (charts, warning summary, CSV) under

/* Search over BOTH levels in one box. Communes must be disambiguated by
   province — names like Tan Thanh / Tan Thanh repeat across provinces — so
   every commune row shows its province. Picking a result switches the display
   mode to match the result's level, then zooms to the unit's own bounds. */
function Search({
  geo,
  onPick
}) {
  const [q, setQ] = useState("");
  const hits = useMemo(() => {
    const t = norm(q.trim());
    if (t.length < 2) return [];
    const out = [];
    const scan = (fc, level) => {
      if (!fc || !fc.features) return;
      for (const f of fc.features) {
        if (out.length >= 60) return;
        if (norm(f.properties.ten).includes(t)) out.push({
          f,
          level
        });
      }
    };
    scan(geo && geo.tinh, "tinh"); // provinces first: fewer, broader
    scan(geo && geo.xa, "xa");
    return out;
  }, [q, geo]);
  return /*#__PURE__*/React.createElement("div", {
    className: "card searchbox"
  }, /*#__PURE__*/React.createElement("input", {
    value: q,
    onChange: e => setQ(e.target.value),
    placeholder: "T\xECm t\u1EC9nh / th\xE0nh, ph\u01B0\u1EDDng / x\xE3\u2026"
  }), hits.length > 0 && /*#__PURE__*/React.createElement("div", {
    className: "card results"
  }, hits.map(({
    f,
    level
  }) => /*#__PURE__*/React.createElement("button", {
    key: level + "-" + f.properties.id,
    onClick: () => {
      setQ("");
      onPick(f.properties, level);
    }
  }, /*#__PURE__*/React.createElement("span", {
    className: "tag"
  }, level === "tinh" ? "Tỉnh/Thành" : f.properties.loai || "Xã"), /*#__PURE__*/React.createElement("div", null, f.properties.ten), level === "xa" && /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, f.properties.ten_tinh)))));
}

// adminvn/ (built by process_admin_html.py, mirrored from QPF-adminVN).
// This card opens it in a new tab or downloads the self-contained file.
// Ô lưới (grid) mode keeps its in-app VForce-cast point series (GridDetail).
function UnitCard({
  unit,
  pages,
  onClose,
  ver
}) {
  const level = unit.tinh ? "xa" : "tinh";
  const rel = pages && pages[level] ? pages[level][unit.id] : null;
  // Cache-bust: the unit page is self-contained with this run's forecast
  // embedded, so an un-versioned URL can serve a stale cached copy.
  const href = rel ? "adminvn/" + rel + "?v=" + encodeURIComponent(ver || "") : null;
  const file = rel ? rel.split("/").pop() : "";
  return /*#__PURE__*/React.createElement("aside", {
    className: "drawer",
    style: {
      width: 360
    }
  }, /*#__PURE__*/React.createElement("header", null, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h2", null, unit.ten), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, [unit.loai, unit.ten_tinh].filter(Boolean).join(" · ") || "Tỉnh / Thành phố")), /*#__PURE__*/React.createElement("button", {
    className: "xbtn",
    onClick: onClose,
    "aria-label": "Dong"
  }, "\xD7")), /*#__PURE__*/React.createElement("div", {
    className: "body"
  }, href ? /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      fontSize: 12.5,
      marginTop: 0
    }
  }, "Trang chi ti\u1EBFt c\u1EE7a \u0111\u01A1n v\u1ECB n\xE0y g\u1ED3m: t\xF3m t\u1EAFt c\u1EA3nh b\xE1o, b\u1EA3n \u0111\u1ED3 ranh gi\u1EDBi & tr\u01B0\u1EDDng m\u01B0a theo \xF4 l\u01B0\u1EDBi, chu\u1ED7i th\u1EDDi gian, x\xE1c su\u1EA5t m\u01B0a l\u1EDBn, bi\u1EC3u \u0111\u1ED3 h\u1ED9p v\xE0 t\u1EA3i CSV. Trang l\xE0 m\u1ED9t t\u1EC7p HTML t\u1EF1 ch\u1EE9a \u2014 t\u1EA3i v\u1EC1 v\u1EABn m\u1EDF \u0111\u01B0\u1EE3c kh\xF4ng c\u1EA7n m\u1EA1ng."), /*#__PURE__*/React.createElement("a", {
    className: "csvbtn",
    style: {
      display: "inline-block",
      textDecoration: "none",
      marginRight: 8
    },
    href: href,
    target: "_blank",
    rel: "noopener"
  }, "M\u1EDF trang chi ti\u1EBFt \u2197"), /*#__PURE__*/React.createElement("a", {
    className: "csvbtn",
    style: {
      display: "inline-block",
      textDecoration: "none",
      background: "#2a3542"
    },
    href: href,
    download: file
  }, "\u2913 T\u1EA3i v\u1EC1 (HTML)")) : /*#__PURE__*/React.createElement("p", {
    className: "hint"
  }, "Trang chi ti\u1EBFt c\u1EE7a \u0111\u01A1n v\u1ECB n\xE0y ch\u01B0a s\u1EB5n s\xE0ng (\u0111ang \u0111\u01B0\u1EE3c c\u1EADp nh\u1EADt theo chu k\u1EF3 d\u1EF1 b\xE1o).")));
}

/* ------------------------------------------------- grid-cell (Ô lưới) drawer */
// The point query for Ô lưới mode: the VForce-cast click grids give a
// cumulative q50/q90 and a per-interval bucket at one 0.1 deg cell, for every
// lead out to 48 h. Values are integer tenths -> multiply by `scale`.
function GridDetail({
  point,
  onClose,
  model,
  models
}) {
  if (!point) return null;
  const s = point.series || [];
  const has = s.some(p => p.q50 !== null && p.q50 !== undefined);
  const w = 452,
    h = 200,
    ih = h - PAD.t - PAD.b,
    iw = w - PAD.l - PAD.r;
  const ymax = niceMax(Math.max(...s.map(p => p.q90 || 0), 0), 4, 10);
  const t0 = Date.parse(s[0]?.valid_ict || 0),
    t1 = Date.parse(s[s.length - 1]?.valid_ict || 0);
  const X = t => PAD.l + iw * (t - t0) / Math.max(1, t1 - t0);
  const Y = v => PAD.t + ih * (1 - Math.min(v, ymax) / ymax);
  const line = k => s.filter(p => p[k] != null).map(p => `${X(Date.parse(p.valid_ict))},${Y(p[k])}`).join(" ");
  const rate = s.map(p => (p.bucket || 0) / (p.interval_h || 1));
  const rmax = niceMax(Math.max(...rate, 0), 4, 2);
  return /*#__PURE__*/React.createElement("aside", {
    className: "drawer"
  }, /*#__PURE__*/React.createElement("header", null, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h2", null, point.place && (point.place.commune || point.place.province) ? point.place.commune || point.place.province : "Ô lưới"), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, /*#__PURE__*/React.createElement("b", null, "VForce-cast"), " t\u1EA1i \u0111i\u1EC3m"), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, point.place && [point.place.commune && point.place.province ? point.place.province : null, point.place.country].filter(Boolean).join(" · ")), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, point.lat.toFixed(3), "\xB0N, ", point.lon.toFixed(3), "\xB0E", " · ô lưới 0,1°")), /*#__PURE__*/React.createElement("button", {
    className: "xbtn",
    onClick: onClose,
    "aria-label": "Dong"
  }, "\xD7")), /*#__PURE__*/React.createElement("div", {
    className: "body"
  }, !has && /*#__PURE__*/React.createElement("div", {
    className: "vfnote"
  }, "\xD4 l\u01B0\u1EDBi n\xE0y kh\xF4ng c\xF3 gi\xE1 tr\u1ECB VForce-cast."), has && /*#__PURE__*/React.createElement(React.Fragment, null, model !== "vforce" && /*#__PURE__*/React.createElement("div", {
    className: "vfnote",
    style: {
      background: "#fff3cd",
      borderColor: "#ffe08a",
      color: "#6b5400"
    }
  }, "B\u1EA3n \u0111\u1ED3 \u0111ang hi\u1EC3n th\u1ECB ", /*#__PURE__*/React.createElement("b", null, (models.find(m => m.id === model) || {}).short_vi || model), " tr\xEAn l\u01B0\u1EDBi ", /*#__PURE__*/React.createElement("b", null, "0,25\xB0"), ", nh\u01B0ng chu\u1ED7i th\u1EDDi gian t\u1EA1i \u0111i\u1EC3m ch\u1EC9 c\xF3 cho ", /*#__PURE__*/React.createElement("b", null, "VForce-cast"), "(l\u01B0\u1EDBi 0,1\xB0). D\xF9ng ch\u1EBF \u0111\u1ED9 ", /*#__PURE__*/React.createElement("b", null, "T\u1EC9nh/Th\xE0nh"), " ho\u1EB7c ", /*#__PURE__*/React.createElement("b", null, "Ph\u01B0\u1EDDng/X\xE3"), " \u0111\u1EC3 xem chu\u1ED7i c\u1EE7a m\u1ECDi ngu\u1ED3n."), /*#__PURE__*/React.createElement("div", {
    className: "vfnote"
  }, "Gi\xE1 tr\u1ECB VForce-cast t\u1EA1i ", /*#__PURE__*/React.createElement("b", null, "m\u1ED9t \xF4 l\u01B0\u1EDBi 0,1\xB0"), " (kh\xF4ng ph\u1EA3i trung b\xECnh theo di\u1EC7n t\xEDch nh\u01B0 ch\u1EBF \u0111\u1ED9 T\u1EC9nh/X\xE3). H\u1EA1n d\u1EF1 b\xE1o 120 gi\u1EDD; b\u01B0\u1EDBc 3 gi\u1EDD \u0111\u1EBFn +48h, sau \u0111\xF3 6 gi\u1EDD."), /*#__PURE__*/React.createElement("div", {
    className: "chart"
  }, /*#__PURE__*/React.createElement("h3", null, "M\u01B0a c\u1ED9ng d\u1ED3n t\u1EEB gi\u1EDD ph\xE1t tin"), /*#__PURE__*/React.createElement("p", {
    className: "cap"
  }, "\u0110\u01B0\u1EDDng \u0111\u1EADm = Q50, \u0111\u01B0\u1EDDng nh\u1EA1t = Q90 (k\u1ECBch b\u1EA3n c\u1EF1c \u0111oan)."), /*#__PURE__*/React.createElement("svg", {
    width: "100%",
    viewBox: `0 0 ${w} ${h}`,
    role: "img"
  }, /*#__PURE__*/React.createElement(Axes, {
    w: w,
    h: h,
    ymax: ymax,
    unit: "mm",
    xLabels: [],
    thresholds: [{
      value: 50,
      label: "Nguy hiểm",
      color: "#ef5b8c"
    }, {
      value: 100,
      label: "Rất nguy hiểm",
      color: "#a8324a"
    }]
  }), /*#__PURE__*/React.createElement("polyline", {
    points: line("q90"),
    fill: "none",
    stroke: "#2f8fe0",
    strokeWidth: "1.4",
    strokeDasharray: "4 3"
  }), /*#__PURE__*/React.createElement("polyline", {
    points: line("q50"),
    fill: "none",
    stroke: "#1d4e89",
    strokeWidth: "2"
  }))), /*#__PURE__*/React.createElement("div", {
    className: "chart"
  }, /*#__PURE__*/React.createElement("h3", null, "C\u01B0\u1EDDng \u0111\u1ED9 m\u01B0a theo b\u01B0\u1EDBc"), /*#__PURE__*/React.createElement("p", {
    className: "cap"
  }, "mm/gi\u1EDD trong m\u1ED7i kho\u1EA3ng d\u1EF1 b\xE1o (1 gi\u1EDD cho 6 gi\u1EDD \u0111\u1EA7u, sau \u0111\xF3 3 gi\u1EDD)."), /*#__PURE__*/React.createElement("svg", {
    width: "100%",
    viewBox: `0 0 ${w} ${h}`,
    role: "img"
  }, /*#__PURE__*/React.createElement(Axes, {
    w: w,
    h: h,
    ymax: rmax,
    unit: "mm/h",
    xLabels: []
  }), s.map((p, i) => {
    const x = PAD.l + iw * (i + 0.5) / s.length;
    const bw = Math.max(2, iw / s.length - 2);
    const yv = PAD.t + (h - PAD.t - PAD.b) * (1 - Math.min(rate[i], rmax) / rmax);
    return /*#__PURE__*/React.createElement("rect", {
      key: i,
      x: x - bw / 2,
      y: yv,
      width: bw,
      height: Math.max(0.6, PAD.t + (h - PAD.t - PAD.b) - yv),
      fill: "#1d91c0",
      rx: "1.5"
    });
  }))), /*#__PURE__*/React.createElement("table", {
    className: "popup-tbl",
    style: {
      width: "100%"
    }
  }, /*#__PURE__*/React.createElement("thead", null, /*#__PURE__*/React.createElement("tr", null, /*#__PURE__*/React.createElement("th", null, "H\u1EA1n"), /*#__PURE__*/React.createElement("th", null, "\u0110\u1EBFn l\xFAc"), /*#__PURE__*/React.createElement("th", null, "Q50"), /*#__PURE__*/React.createElement("th", null, "Q90"), /*#__PURE__*/React.createElement("th", null, "mm/h"))), /*#__PURE__*/React.createElement("tbody", null, s.map((p, i) => /*#__PURE__*/React.createElement("tr", {
    key: i
  }, /*#__PURE__*/React.createElement("td", null, "+", p.h, "h"), /*#__PURE__*/React.createElement("td", null, hhmm(p.valid_ict), " ", dm(p.valid_ict)), /*#__PURE__*/React.createElement("td", null, num(p.q50, 1)), /*#__PURE__*/React.createElement("td", null, num(p.q90, 1)), /*#__PURE__*/React.createElement("td", null, num(rate[i], 1)))))), /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 8
    }
  }, "Q50/Q90 l\xE0 m\u01B0a ", /*#__PURE__*/React.createElement("b", null, "c\u1ED9ng d\u1ED3n"), " k\u1EC3 t\u1EEB gi\u1EDD ph\xE1t tin."))));
}

/* --------------------------------------------------------------- panels */
function Legend({
  meta,
  mode,
  model,
  field,
  tile
}) {
  const bins = binsFor(field, meta.legend);
  const what = field === "int" ? "cường độ mưa (mm/giờ) — Q50 (ô lưới thô)" : field === "cum" ? "mưa cộng dồn từ giờ phát tin — Q50 (ô lưới thô)" : field === "x50" ? "khả năng mưa vượt 50 mm/24 giờ" : field === "q90" ? "tổng mưa 24 giờ — kịch bản cực đoan" : "tổng mưa 24 giờ — kịch bản điển hình";
  const how = mode === "grid" ? "giá trị từng ô lưới thô" : "trung bình theo diện tích trên từng đơn vị hành chính";
  return /*#__PURE__*/React.createElement("div", {
    className: "card pad"
  }, /*#__PURE__*/React.createElement("p", {
    className: "title",
    style: {
      marginBottom: 2
    }
  }, FIELDS[field].label), /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 0,
      marginBottom: 6
    }
  }, what, " \xB7 ", how, tile ? ` · ${tile}` : ""), bins.map((b, i) => /*#__PURE__*/React.createElement("div", {
    className: "legend-row",
    key: i
  }, /*#__PURE__*/React.createElement("span", {
    className: "swatch",
    style: {
      background: b.color
    }
  }), /*#__PURE__*/React.createElement("span", null, b.label))));
}
// Two texts ship in bulletin.json: `text` leads with VForce-cast, and
// `ensemble_text` is the multi-model version — show whichever matches the
// selected source, falling back to the other when only one is present.
function Bulletin({
  bulletin,
  meta,
  model
}) {
  const [open, setOpen] = useState(false);
  const useVf = model === "vforce" ? !!bulletin.text : !bulletin.ensemble_text;
  const body = (useVf ? bulletin.text : bulletin.ensemble_text) || "";
  const src = useVf ? bulletin.source : bulletin.ensemble_source || bulletin.source;
  useEffect(() => {
    setOpen(false);
  }, [body]);
  if (!body) return null;
  const long = body.length > 180;
  const short = long ? body.slice(0, 165).replace(/\s\S*$/, "") + " …" : body;
  return /*#__PURE__*/React.createElement("div", {
    className: "card pad"
  }, /*#__PURE__*/React.createElement("p", {
    className: "title"
  }, "Nh\u1EADn \u0111\u1ECBnh b\u1EA3n tin"), /*#__PURE__*/React.createElement("div", {
    style: {
      whiteSpace: "pre-wrap",
      fontSize: 12.5,
      lineHeight: 1.55
    }
  }, open || !long ? body : short), long && /*#__PURE__*/React.createElement("button", {
    className: "btn-link",
    onClick: () => setOpen(!open)
  }, open ? "Thu gọn" : "Xem đầy đủ"), /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 8
    }
  }, "Ph\xE1t tin ", hhmm(meta.issued_ict || meta.init_ict), " ICT ", dmy((meta.issued_ict || meta.init_ict).slice(0, 10)), src === "gemini" ? " · Nhận định tự động bởi AI Gemini" : " · Nhận định tự động từ dữ liệu khí tượng"));
}
/* ------------------------------------------------------------------ app */
function App() {
  const [meta, setMeta] = useState(null),
    [tmeta, setTmeta] = useState(null);
  const [geo, setGeo] = useState({}),
    [frames, setFrames] = useState(null),
    [gm, setGm] = useState(null);
  const [mode, setMode] = useState("tinh");
  const [zoomTo, setZoomTo] = useState(null);
  // Phones: the panel covers the map, so start it collapsed there. Collapse
  // only when the viewport is KNOWN to be narrow — innerWidth can report 0
  // (hidden/not-yet-composited frame), and treating that as a phone would
  // start every desktop visit collapsed.
  const [panelOpen, setPanelOpen] = useState(() => {
    const w = typeof window === "undefined" ? 0 : window.innerWidth;
    return !(w > 0 && w <= 720);
  });
  const [model, setModel] = useState("ensemble"),
    [field, setField] = useState("q50"),
    [idx, setIdx] = useState(0);
  const [playing, setPlaying] = useState(false),
    [bulletin, setBulletin] = useState(null);
  const [focus, setFocus] = useState(null),
    [unitData, setUnitData] = useState(null);
  const [gridPoint, setGridPoint] = useState(null),
    [pages, setPages] = useState(null);
  const [tc, setTc] = useState(null);
  const seriesCache = useRef({}),
    gridCache = useRef(null),
    nowMan = useRef(null),
    adminRef = useRef(null);
  useEffect(() => {
    (async () => {
      // v2.json, not latest.json: process_vn.py writes its own v1-format
      // latest.json into this same folder and the shapes differ
      const m = await j("v2.json?t=" + Date.now());
      const v = "?v=" + encodeURIComponent(m.created_utc);
      // gm_frames is optional — the manifest drops the vforce source when
      // gmfcast has not produced a cycle, so a 404 here must not kill the app
      const [tm, fr, tg, g] = await Promise.all([j("tiles/meta.json" + v), j("data/frames.json" + v), j("static/tinh.geojson" + v), m.gm ? j("data/gm_frames.json" + v).catch(() => null) : Promise.resolve(null)]);
      setMeta(m);
      setTmeta(tm);
      setFrames(fr);
      setGm(g);
      setGeo({
        tinh: tg
      });
      j("static/xa.geojson" + v).then(x => setGeo(p => _objectSpread(_objectSpread({}, p), {}, {
        xa: x
      }))).catch(() => {});
      j("static/adm1_foreign.geojson" + v).then(x => setGeo(p => _objectSpread(_objectSpread({}, p), {}, {
        adm1: x
      }))).catch(() => {});
      fetch("bulletin.json" + v).then(r => r.ok ? r.json() : null).then(b => b && setBulletin(b)).catch(() => {});
      // unit id -> standalone page path (mirrored from QPF-adminVN)
      fetch("adminvn/pages.json" + v).then(r => r.ok ? r.json() : null).then(p => p && setPages(p)).catch(() => {});
      // active-cyclone tracks (process_tc.py) — optional, quiet season = absent
      fetch("tc.json" + v).then(r => r.ok ? r.json() : null).then(t => t && setTc(t)).catch(() => {});
    })().catch(e => {
      document.getElementById("root").innerHTML = '<div class="loading">Lỗi tải dữ liệu: ' + e.message + '</div>';
    });
  }, []);

  // Clicking a unit only highlights it and opens the link card — detail
  // lives on the unit's standalone page under adminvn/ (no series fetch).
  const pickUnit = React.useCallback(props => {
    setFocus(props);
  }, []);
  // Search result: switch the display mode to the result's level, select it,
  // and zoom. Grid mode has no unit selection, so a pick always leaves it.
  const pickSearch = React.useCallback((props, level) => {
    setMode(level);
    setIdx(0);
    setUnitData(null);
    setFocus(props);
    setZoomTo(z => ({
      bounds: props.bounds,
      n: (z ? z.n : 0) + 1
    }));
  }, []);

  // Ô lưới point query: fetch every lead grid once (cached for the session),
  // then index the clicked cell. Values are integer tenths -> apply `scale`.
  const pickGrid = React.useCallback(async latlng => {
    if (!meta) return;
    setGridPoint({
      lat: latlng.lat,
      lon: latlng.lng,
      series: [],
      loading: true
    });
    try {
      if (!nowMan.current) nowMan.current = await j("nowcast/manifest.json?v=" + encodeURIComponent(meta.created_utc));
      const man = nowMan.current;
      if (!gridCache.current) {
        const v = "?v=" + encodeURIComponent(man.issue_utc);
        gridCache.current = Promise.all(man.leads.map((_, k) => j(`nowcast/grids/${String(k).padStart(2, "0")}.json${v}`)));
      }
      const grids = await gridCache.current,
        g0 = grids[0];
      const i = Math.round((g0.lat0 - latlng.lat) / -g0.dlat),
        jx = Math.round((latlng.lng - g0.lon0) / g0.dlon);
      if (i < 0 || i >= g0.nlat || jx < 0 || jx >= g0.nlon) {
        setGridPoint(null);
        return;
      }
      const flat = i * g0.nlon + jx;
      const sc = g => g.scale ?? 1;
      const series = man.leads.map((l, k) => ({
        h: l.h,
        valid_ict: l.valid_ict,
        interval_h: l.interval_h,
        q50: grids[k].q50[flat] * sc(grids[k]),
        q90: grids[k].q90[flat] * sc(grids[k]),
        bucket: grids[k].bucket[flat] * sc(grids[k])
      }));
      // admin.json shares the click grid's geometry and maps each cell to
      // [commune, province, country] (any part may be "" — no commune outside
      // Vietnam). Older files stored only 2 parts, hence the length check.
      let place = null;
      if (!adminRef.current) adminRef.current = j("nowcast/admin.json?v=" + encodeURIComponent(man.issue_utc)).catch(() => null);
      const a = await adminRef.current;
      if (a) {
        const ai = Math.round((a.lat0 - latlng.lat) / -a.dlat),
          aj = Math.round((latlng.lng - a.lon0) / a.dlon);
        if (ai >= 0 && ai < a.nlat && aj >= 0 && aj < a.nlon) {
          const t = a.idx[ai * a.nlon + aj];
          if (t >= 0) {
            const n = a.names[t] || [];
            place = n.length >= 3 ? {
              commune: n[0] || "",
              province: n[1] || "",
              country: n[2] || ""
            } : {
              commune: "",
              province: n[0] || "",
              country: n[1] || ""
            };
          }
        }
      }
      setGridPoint({
        lat: latlng.lat,
        lon: latlng.lng,
        series,
        place
      });
    } catch (e) {
      setGridPoint(null);
    }
  }, [meta]);

  // The TC player aligns WHATEVER the user is looking at to the cyclone's
  // valid time: it never changes the mode / source / field, only the frame
  // index on the current selection's own time axis (window fields align on
  // window end, step fields on the step time).
  const tileTimes = useMemo(() => {
    if (!meta) return [];
    if (mode === "grid") {
      if (!tmeta) return [];
      const M = tmeta.models[model];
      if (!M) return [];
      if (FIELDS[field].kind === "win") return (M.windows || []).map(w => Date.parse(w.end));
      return (M.steps || []).map(s => Date.parse(s));
    }
    if (model === "vforce") return (meta.gm && meta.gm.windows || []).map(w => Date.parse(w.end));
    const MW = (meta.model_windows || {})[model];
    if (MW) return MW.map(w => Date.parse(w.end));
    return (meta.windows || []).map(d => Date.parse(d));
  }, [meta, tmeta, mode, model, field]);
  // Who moved first decides the coupling: if the user starts with the TC
  // player before touching any rain control, the rain map defaults to
  // Ô lưới / Tổ hợp / per-step intensity (the natural companion view); once
  // they have driven the rain side themselves (timeline, mode, source or
  // field), the TC player only aligns the frame on THEIR selection's axis.
  const rainTouched = useRef(false);
  const tcLead = React.useCallback((h, validMs) => {
    if (!rainTouched.current && tmeta) {
      // Companion view when the cyclone player leads: VForce-cast per-step
      // intensity (radar-anchored, highest resolution), falling back to Tổ
      // hợp only when VForce-cast has no cycle this run.
      const prefer = (tmeta.models["vforce"] || {}).fields?.includes("int") ? "vforce" : "ensemble";
      const M = tmeta.models[prefer];
      if (M && M.fields.includes("int")) {
        setMode("grid");
        setModel(prefer);
        setField("int");
        const steps = M.steps || [];
        let si = -1,
          sd = Infinity;
        steps.forEach((s, i) => {
          const d = Math.abs(Date.parse(s) - validMs);
          if (d < sd) {
            sd = d;
            si = i;
          }
        });
        if (si >= 0 && sd <= 3 * 3600e3 + 6e4) setIdx(si);
        return;
      }
    }
    let bi = -1,
      bd = Infinity;
    tileTimes.forEach((t, i) => {
      const d = Math.abs(t - validMs);
      if (d < bd) {
        bd = d;
        bi = i;
      }
    });
    // only move when the cyclone time actually falls on this axis (within
    // half the axis spacing) — beyond it, keep the user's frame
    const sp = tileTimes.length > 1 ? tileTimes[1] - tileTimes[0] : 24 * 3600e3;
    if (bi >= 0 && bd <= sp / 2 + 6e4) setIdx(bi);
  }, [tileTimes, tmeta]);
  // current frame's valid time (+gate = half the axis spacing): the map
  // pushes this into the cyclone overlay so its display follows the rain
  // timeline (reverse of tcLead)
  const tcSync = useMemo(() => {
    const t = tileTimes[idx];
    if (!t) return null;
    const sp = tileTimes.length > 1 ? tileTimes[1] - tileTimes[0] : 24 * 3600e3;
    return {
      t,
      gate: sp / 2 + 6e4
    };
  }, [tileTimes, idx]);

  // which fields the current mode+source can actually show
  const avail = useMemo(() => {
    if (!meta) return [];
    if (mode === "grid") return tmeta?.models[model]?.fields || [];
    return model === "vforce" ? meta.gm?.fields || ["q50", "q90"] : UNIT_FIELDS;
  }, [meta, tmeta, mode, model]);
  useEffect(() => {
    if (avail.length && !avail.includes(field)) setField(avail.includes("q50") ? "q50" : avail[0]);
  }, [avail, field]);
  const tiles = useMemo(() => {
    if (!meta) return [];
    if (mode === "grid") {
      if (!tmeta) return [];
      const M = tmeta.models[model];
      if (!M) return [];
      // windows: the SELECTED source's own axis; steps: lead from the SAME
      // per-model anchor the windows use (M.anchor_ict, shipped with the
      // tiles by process_dam — a 6-hourly model reads +6/+12/... in line
      // with its +24/+48 windows). Never meta.issued_ict first: a blend/
      // nowcast hour reissues gmfcast without rebuilding the tiles, and
      // labeling this older axis with the fresher issue shifted every lead.
      if (FIELDS[field].kind === "win") return winTiles(M.windows);
      return stepTiles(M.steps, M.anchor_ict || tmeta.issued_ict || meta.issued_ict || meta.init_ict);
    }
    if (model === "vforce") return winTiles(meta.gm && meta.gm.windows);
    // admin mode labels the SELECTED source's own window axis (model_windows,
    // like the dam site's tmeta.models[src].windows): a 6-hourly model's ends
    // differ from the shared ensemble axis, and its frames are indexed on its
    // own axis. Fall back to the ensemble axis for a pre-model_windows v2.json.
    const MW = (meta.model_windows || {})[model];
    if (MW) return winTiles(MW);
    return meta.windows.map(d => ({
      top: `+${Math.round((Date.parse(d) - Date.parse(meta.issued_ict || meta.init_ict)) / 36e5)}h`,
      bot: `${dow(d)} ${dmy(d)} · ${hhmm(d)}`
    }));
  }, [meta, tmeta, mode, model, field]);
  useEffect(() => {
    if (idx >= tiles.length) setIdx(0);
  }, [tiles.length]);
  useEffect(() => {
    if (!playing || !tiles.length) return;
    const t = setInterval(() => setIdx(i => (i + 1) % tiles.length), 900);
    return () => clearInterval(t);
  }, [playing, tiles.length]);
  if (!meta || !tmeta || !frames) return /*#__PURE__*/React.createElement("div", {
    className: "loading"
  }, "\u0110ang t\u1EA3i d\u1EEF li\u1EC7u d\u1EF1 b\xE1o\u2026");
  const tile = tiles[idx] ? `${tiles[idx].top} · ${tiles[idx].bot}` : "";
  // The model note (v2.json) now covers the grid-mode / 24-h areal-mean caveat,
  // so the separate per-mode hint is no longer shown.
  const unitHint = null;
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(MapPane, {
    mode: mode,
    meta: meta,
    tmeta: tmeta,
    geo: geo,
    frames: frames,
    gm: gm,
    model: model,
    field: field,
    frameIdx: idx,
    ver: meta.created_utc,
    winCount: tiles.length,
    onPick: pickUnit,
    focusId: focus ? focus.id : null,
    onPickGrid: pickGrid,
    zoomTo: zoomTo,
    tc: tc,
    onTcLead: tcLead,
    tcSync: tcSync
  }), /*#__PURE__*/React.createElement("div", {
    className: "float topleft" + (panelOpen ? "" : " collapsed")
  }, /*#__PURE__*/React.createElement("div", {
    className: "stack" + (panelOpen ? "" : " collapsed")
  }, /*#__PURE__*/React.createElement("div", {
    className: "card brand"
  }, /*#__PURE__*/React.createElement("button", {
    className: "ptoggle",
    onClick: () => setPanelOpen(o => !o),
    "aria-expanded": panelOpen,
    title: panelOpen ? "Thu gọn bảng điều khiển" : "Mở bảng điều khiển",
    "aria-label": panelOpen ? "Thu gọn bảng điều khiển" : "Mở bảng điều khiển"
  }, panelOpen ? "\u2715" : "\u2630"), /*#__PURE__*/React.createElement("h1", null, "D\u1EF1 b\xE1o m\u01B0a t\u1ED5 h\u1EE3p Vi\u1EC7t Nam"), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, "Ph\xE1t tin ", hhmm(meta.issued_ict || meta.init_ict), " ICT ", dmy((meta.issued_ict || meta.init_ict).slice(0, 10))), /*#__PURE__*/React.createElement("div", {
    className: "sub",
    style: {
      marginTop: 2,
      opacity: .75
    }
  }, "Chu kỳ mô hình: ", meta.models.filter(m => m.init_ict || m.issue_ict).map(m => `${m.short_vi} ${hhmm(m.init_ict || m.issue_ict)} ${dm(m.init_ict || m.issue_ict)}`).join(" · "))), /*#__PURE__*/React.createElement(TcBanner, {
    tc: tc
  }), /*#__PURE__*/React.createElement(Search, {
    geo: geo,
    onPick: pickSearch
  }), /*#__PURE__*/React.createElement("div", {
    className: "card pad",
    style: {
      paddingTop: 8,
      paddingBottom: 8
    }
  }, /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      margin: 0
    }
  }, "Bản đồ ưu tiên: ", /*#__PURE__*/React.createElement("a", {
    href: "adminvn/overview_tinh.html?v=" + encodeURIComponent(meta.created_utc),
    target: "_blank",
    rel: "noopener"
  }, "tỉnh/thành ↗"), " · ", /*#__PURE__*/React.createElement("a", {
    href: "adminvn/overview_xa.html?v=" + encodeURIComponent(meta.created_utc),
    target: "_blank",
    rel: "noopener"
  }, "xã/phường ↗"))), /*#__PURE__*/React.createElement("div", {
    className: "card pad"
  }, /*#__PURE__*/React.createElement("p", {
    className: "lbl"
  }, "Ki\u1EC3u hi\u1EC3n th\u1ECB"), /*#__PURE__*/React.createElement("div", {
    className: "seg"
  }, MODES.map(m => /*#__PURE__*/React.createElement("button", {
    key: m.key,
    className: mode === m.key ? "on" : "",
    onClick: () => {
      rainTouched.current = true;
      setMode(m.key);
      setIdx(0);
      setFocus(null);
      setUnitData(null);
      setGridPoint(null);
    }
  }, m.label))), /*#__PURE__*/React.createElement("p", {
    className: "lbl",
    style: {
      marginTop: 12
    }
  }, "M\xF4 h\xECnh d\u1EF1 b\xE1o"), /*#__PURE__*/React.createElement("div", {
    className: "seg mdl",
    style: {
      "--mc": MODEL_COLOR[model]
    }
  }, meta.models.map(m => /*#__PURE__*/React.createElement("button", {
    key: m.id,
    className: model === m.id ? "on" : "",
    style: model === m.id ? {
      "--mc": MODEL_COLOR[m.id],
      "--mct": m.id === "ensemble" ? "#3d3000" : "#fff"
    } : {},
    onClick: () => {
      rainTouched.current = true;
      setModel(m.id);
      setIdx(0);
    }
  }, m.short_vi))), /*#__PURE__*/React.createElement("p", {
    className: "lbl",
    style: {
      marginTop: 12
    }
  }, "Th\xF4ng tin hi\u1EC3n th\u1ECB"), /*#__PURE__*/React.createElement("div", {
    className: "seg"
  }, FIELD_ORDER.map(k => {
    const f = FIELDS[k];
    const ok = avail.includes(k);
    return /*#__PURE__*/React.createElement("button", {
      key: k,
      className: field === k ? "on" : "",
      disabled: !ok,
      onClick: () => {
        rainTouched.current = true;
        setField(k);
        setIdx(0);
      }
    }, f.label);
  })), unitHint && /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 8
    }
  }, unitHint), mode === "grid" && /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 8
    }
  }, "Nh\u1EA5p v\xE0o b\u1EA3n \u0111\u1ED3 \u0111\u1EC3 xem chu\u1ED7i th\u1EDDi gian VForce-cast t\u1EA1i \xF4 l\u01B0\u1EDBi \u0111\xF3."), /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 8
    }
  }, meta.note), /*#__PURE__*/React.createElement(OffGridNote, {
    models: meta.models,
    model: model
  })), /*#__PURE__*/React.createElement(Legend, {
    meta: meta,
    mode: mode,
    model: model,
    field: field,
    tile: tile
  }), bulletin && /*#__PURE__*/React.createElement(Bulletin, {
    bulletin: bulletin,
    meta: meta,
    model: model
  }), /*#__PURE__*/React.createElement(Credit, null))), /*#__PURE__*/React.createElement(Timeline, {
    tiles: tiles,
    idx: idx,
    playing: playing,
    setIdx: i => {
      rainTouched.current = true;
      setIdx(i);
    },
    setPlaying: p => {
      rainTouched.current = true;
      setPlaying(p);
    }
  }), focus && mode !== "grid" && /*#__PURE__*/React.createElement(UnitCard, {
    unit: focus,
    pages: pages,
    ver: meta.created_utc,
    onClose: () => {
      setFocus(null);
      setUnitData(null);
    }
  }), gridPoint && mode === "grid" && /*#__PURE__*/React.createElement(GridDetail, {
    point: gridPoint,
    model: model,
    models: meta.models,
    onClose: () => setGridPoint(null)
  }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
